services:
  db:
    image: postgres:18
    container_name: local_llm_server_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: local_llm_server_postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql
    restart: unless-stopped

  pgadmin4:
    image: dpage/pgadmin4:9
    container_name: local_llm_server_pgadmin4
    ports:
      - 8080:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./config/servers.json:/pgadmin4/servers.json
    environment:
      PGADMIN_DEFAULT_EMAIL: user@example.com
      PGADMIN_DEFAULT_PASSWORD: pass
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    depends_on:
      - db

volumes:
  pg_data:
  pgadmin_data:
