"""chat completions

Revision ID: 14214498735f
Revises: 372cd15bf23f
Create Date: 2026-10-03 20:51:11.180406

"""

from collections.abc import Sequence
from datetime import UTC, datetime

import sqlalchemy as sa
from alembic import op
from db.types import UtcDateTime

# revision identifiers, used by Alembic.
revision: str = "14214498735f"
down_revision: str | Sequence[str] | None = "372cd15bf23f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_completion_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("created_at", UtcDateTime(timezone=True), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "succeeded",
                "failed",
                "cancelled",
                name="chatcompletionstatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("stream", sa.Boolean(), nullable=False),
        sa.Column("n", sa.Integer(), nullable=False),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=False),
        sa.Column("time_to_first_token_ms", sa.Integer(), nullable=True),
        sa.Column("generation_duration_ms", sa.Integer(), nullable=True),
        sa.Column("load_duration_ms", sa.Integer(), nullable=True),
        sa.Column("finish_reason", sa.String(), nullable=True),
        sa.Column("error_type", sa.String(), nullable=True),
        sa.Column("error_code", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_completion_records")),
        sa.UniqueConstraint(
            "external_id", name=op.f("uq_chat_completion_records_external_id")
        ),
    )
    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("created_at", UtcDateTime(timezone=True), nullable=False),
        sa.Column("owned_by", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_models")),
        sa.UniqueConstraint("external_id", name=op.f("uq_models_external_id")),
    )
    op.create_table(
        "chat_completion_contents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("record_id", sa.Integer(), nullable=False),
        sa.Column("request", sa.JSON(), nullable=False),
        sa.Column("response", sa.JSON(none_as_null=True), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["chat_completion_records.id"],
            name=op.f("fk_chat_completion_contents_record_id_chat_completion_records"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_chat_completion_contents")),
        sa.UniqueConstraint(
            "record_id", name=op.f("uq_chat_completion_contents_record_id")
        ),
    )
    op.create_index(
        "ix_chat_completion_records_created_at_id",
        "chat_completion_records",
        [sa.text("created_at DESC"), sa.text("id DESC")],
    )
    models = sa.table(
        "models",
        sa.column("external_id", sa.String),
        sa.column("created_at", UtcDateTime),
        sa.column("owned_by", sa.String),
    )
    op.bulk_insert(
        models,
        [
            {
                "external_id": "qwen3.5:9b",
                "created_at": datetime.now(UTC),
                "owned_by": "qwen",
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_chat_completion_records_created_at_id",
        table_name="chat_completion_records",
    )
    op.drop_table("chat_completion_contents")
    op.drop_table("models")
    op.drop_table("chat_completion_records")
    # ### end Alembic commands ###
