"""batch input file chunks table

Revision ID: 76f6c230d857
Revises: 63fec4091c75
Create Date: 2026-08-22 12:42:31.821588

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "76f6c230d857"
down_revision: str | Sequence[str] | None = "63fec4091c75"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "batch_input_file_chunks",
        sa.Column(
            "batch_input_file_chunk_id",
            sa.UUID(),
            server_default=sa.text("uuidv7()"),
            nullable=False,
        ),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=False),
        sa.Column("start_line", sa.Integer(), nullable=False),
        sa.Column("end_line", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("batch_input_file_chunk_id", "file_id"),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("batch_input_file_chunks", schema="core")
    # ### end Alembic commands ###
