"""files table

Revision ID: 63fec4091c75
Revises: 08bfa03394bf
Create Date: 2026-08-22 12:40:53.645799

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "63fec4091c75"
down_revision: str | Sequence[str] | None = "08bfa03394bf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "files",
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("original_filename", sa.String(), nullable=True),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("format", sa.String(), nullable=False),
        sa.Column("purpose", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("file_id"),
        schema="core",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("files", schema="core")
    # ### end Alembic commands ###
