version: 1

disable_existing_loggers: false

formatters:
  rich:
    format: "%(message)s"

handlers:
  rich:
    class: rich.logging.RichHandler
    formatter: rich
    level: DEBUG
    rich_tracebacks: true
    tracebacks_show_locals: true
    show_path: false
    markup: true

loggers:
  uvicorn:
    level: INFO
    handlers:
      - rich
    propagate: false

  uvicorn.error:
    level: INFO
    handlers:
      - rich
    propagate: false

  uvicorn.access:
    level: INFO
    handlers:
      - rich
    propagate: false

root:
  level: DEBUG
  handlers:
    - rich