/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Health */
        get: operations["get_health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/chat/completions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Chat Completion */
        post: operations["create_chat_completion_v1_chat_completions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Response */
        post: operations["create_response_v1_responses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_v1_analytics_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/requests/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Requests Summary */
        get: operations["get_requests_summary_v1_analytics_requests_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observability/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Requests */
        get: operations["list_requests_v1_observability_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observability/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Request */
        get: operations["get_request_v1_observability_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/observability/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream Events */
        get: operations["stream_events_v1_observability_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalyticsRequestItem */
        AnalyticsRequestItem: {
            /** Id */
            id: string;
            endpoint: components["schemas"]["Endpoint"];
            /** Created */
            created: number;
            /** Model */
            model: string;
            status: components["schemas"]["RequestStatus"];
            /** Stream */
            stream: boolean;
            /** Prompt Tokens */
            prompt_tokens: number | null;
            /** Completion Tokens */
            completion_tokens: number | null;
            /** Total Tokens */
            total_tokens: number | null;
            /** Duration Ms */
            duration_ms: number;
            /** Time To First Token Ms */
            time_to_first_token_ms: number | null;
            /** Generation Duration Ms */
            generation_duration_ms: number | null;
            /** Load Duration Ms */
            load_duration_ms: number | null;
            /** Finish Reason */
            finish_reason: string | null;
            /** Error Type */
            error_type: string | null;
            /** Error Code */
            error_code: string | null;
        };
        /** AnalyticsRequestList */
        AnalyticsRequestList: {
            /**
             * Object
             * @constant
             */
            object: "list";
            /** Data */
            data: components["schemas"]["AnalyticsRequestItem"][];
            /** First Id */
            first_id: string | null;
            /** Last Id */
            last_id: string | null;
            /** Has More */
            has_more: boolean;
        };
        /** AnalyticsRequestSummary */
        AnalyticsRequestSummary: {
            /** Request Count */
            request_count: number;
            /** Error Count */
            error_count: number;
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Avg Duration Ms */
            avg_duration_ms: number | null;
            /** Avg Time To First Token Ms */
            avg_time_to_first_token_ms: number | null;
            /** Avg Generation Duration Ms */
            avg_generation_duration_ms: number | null;
        };
        /** AssistantAudioReference */
        AssistantAudioReference: {
            /** Id */
            id: string;
        };
        /** AudioOutputParameters */
        AudioOutputParameters: {
            /** Voice */
            voice: string | {
                [key: string]: unknown;
            };
            /**
             * Format
             * @enum {string}
             */
            format: "wav" | "aac" | "mp3" | "flac" | "opus" | "pcm16";
        };
        /** ChatCompletionAllowedTools */
        ChatCompletionAllowedTools: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "required";
            /** Tools */
            tools: {
                [key: string]: unknown;
            }[];
        };
        /** ChatCompletionAllowedToolsChoice */
        ChatCompletionAllowedToolsChoice: {
            /**
             * Type
             * @constant
             */
            type: "allowed_tools";
            allowed_tools: components["schemas"]["ChatCompletionAllowedTools"];
        };
        /** ChatCompletionFunctionCallOption */
        ChatCompletionFunctionCallOption: {
            /** Name */
            name: string;
        };
        /** ChatCompletionFunctions */
        ChatCompletionFunctions: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
        };
        /** ChatCompletionMessageCustomToolCall */
        ChatCompletionMessageCustomToolCall: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "custom";
            custom: components["schemas"]["ChatCompletionMessageCustomToolCallBody"];
        };
        /** ChatCompletionMessageCustomToolCallBody */
        ChatCompletionMessageCustomToolCallBody: {
            /** Name */
            name: string;
            /** Input */
            input: string;
        };
        /** ChatCompletionMessageToolCall */
        ChatCompletionMessageToolCall: {
            /** Id */
            id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "function";
            function: components["schemas"]["ChatCompletionMessageToolCallFunction"];
        };
        /** ChatCompletionMessageToolCallFunction */
        ChatCompletionMessageToolCallFunction: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        };
        ChatCompletionMessageToolCalls: (components["schemas"]["ChatCompletionMessageToolCall"] | components["schemas"]["ChatCompletionMessageCustomToolCall"])[];
        /** ChatCompletionNamedToolChoice */
        ChatCompletionNamedToolChoice: {
            /**
             * Type
             * @constant
             */
            type: "function";
            function: components["schemas"]["ChatCompletionNamedToolChoiceFunction"];
        };
        /** ChatCompletionNamedToolChoiceCustom */
        ChatCompletionNamedToolChoiceCustom: {
            /**
             * Type
             * @constant
             */
            type: "custom";
            custom: components["schemas"]["ChatCompletionNamedToolChoiceCustomBody"];
        };
        /** ChatCompletionNamedToolChoiceCustomBody */
        ChatCompletionNamedToolChoiceCustomBody: {
            /** Name */
            name: string;
        };
        /** ChatCompletionNamedToolChoiceFunction */
        ChatCompletionNamedToolChoiceFunction: {
            /** Name */
            name: string;
        };
        /** ChatCompletionRequestAssistantMessage */
        ChatCompletionRequestAssistantMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "assistant";
            /** Content */
            content?: string | components["schemas"]["ChatCompletionRequestAssistantMessageContentPart"][] | null;
            /** Refusal */
            refusal?: string | null;
            /** Name */
            name?: string | null;
            audio?: components["schemas"]["AssistantAudioReference"] | null;
            tool_calls?: components["schemas"]["ChatCompletionMessageToolCalls"] | null;
            function_call?: components["schemas"]["FunctionCall"] | null;
        };
        ChatCompletionRequestAssistantMessageContentPart: components["schemas"]["ChatCompletionRequestMessageContentPartText"] | components["schemas"]["ChatCompletionRequestMessageContentPartRefusal"];
        /** ChatCompletionRequestDeveloperMessage */
        ChatCompletionRequestDeveloperMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "developer";
            /** Content */
            content: string | components["schemas"]["TextParts"];
            /** Name */
            name?: string | null;
        };
        /** ChatCompletionRequestFunctionMessage */
        ChatCompletionRequestFunctionMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "function";
            /** Content */
            content: string | null;
            /** Name */
            name: string;
        };
        ChatCompletionRequestMessage: components["schemas"]["ChatCompletionRequestDeveloperMessage"] | components["schemas"]["ChatCompletionRequestSystemMessage"] | components["schemas"]["ChatCompletionRequestUserMessage"] | components["schemas"]["ChatCompletionRequestAssistantMessage"] | components["schemas"]["ChatCompletionRequestToolMessage"] | components["schemas"]["ChatCompletionRequestFunctionMessage"];
        /** ChatCompletionRequestMessageContentPartAudio */
        ChatCompletionRequestMessageContentPartAudio: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "input_audio";
            input_audio: components["schemas"]["InputAudio"];
            prompt_cache_breakpoint?: components["schemas"]["PromptCacheBreakpointParam"] | null;
        };
        /** ChatCompletionRequestMessageContentPartFile */
        ChatCompletionRequestMessageContentPartFile: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "file";
            file: components["schemas"]["FileContent"];
            prompt_cache_breakpoint?: components["schemas"]["PromptCacheBreakpointParam"] | null;
        };
        /** ChatCompletionRequestMessageContentPartImage */
        ChatCompletionRequestMessageContentPartImage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "image_url";
            image_url: components["schemas"]["ImageUrl"];
            prompt_cache_breakpoint?: components["schemas"]["PromptCacheBreakpointParam"] | null;
        };
        /** ChatCompletionRequestMessageContentPartRefusal */
        ChatCompletionRequestMessageContentPartRefusal: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "refusal";
            /** Refusal */
            refusal: string;
        };
        /** ChatCompletionRequestMessageContentPartText */
        ChatCompletionRequestMessageContentPartText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
            /** Text */
            text: string;
            prompt_cache_breakpoint?: components["schemas"]["PromptCacheBreakpointParam"] | null;
        };
        /** ChatCompletionRequestSystemMessage */
        ChatCompletionRequestSystemMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "system";
            /** Content */
            content: string | components["schemas"]["TextParts"];
            /** Name */
            name?: string | null;
        };
        /** ChatCompletionRequestToolMessage */
        ChatCompletionRequestToolMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "tool";
            /** Content */
            content: string | components["schemas"]["TextParts"];
            /** Tool Call Id */
            tool_call_id: string;
        };
        /** ChatCompletionRequestUserMessage */
        ChatCompletionRequestUserMessage: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            role: "user";
            /** Content */
            content: string | components["schemas"]["ChatCompletionRequestUserMessageContentPart"][];
            /** Name */
            name?: string | null;
        };
        ChatCompletionRequestUserMessageContentPart: components["schemas"]["ChatCompletionRequestMessageContentPartText"] | components["schemas"]["ChatCompletionRequestMessageContentPartImage"] | components["schemas"]["ChatCompletionRequestMessageContentPartAudio"] | components["schemas"]["ChatCompletionRequestMessageContentPartFile"];
        /** ChatCompletionResponseMessage */
        ChatCompletionResponseMessage: {
            /**
             * Role
             * @constant
             */
            role: "assistant";
            /** Content */
            content: string | null;
            /** Refusal */
            refusal?: string | null;
            tool_calls?: components["schemas"]["ChatCompletionMessageToolCalls"] | null;
            function_call?: components["schemas"]["FunctionCall"] | null;
        };
        /** ChatCompletionStreamOptions */
        ChatCompletionStreamOptions: {
            /** Include Usage */
            include_usage?: boolean | null;
            /** Include Obfuscation */
            include_obfuscation?: boolean | null;
        };
        /** ChatCompletionTokenLogprob */
        ChatCompletionTokenLogprob: {
            /** Token */
            token: string;
            /** Logprob */
            logprob: number;
            /** Bytes */
            bytes: number[] | null;
            /** Top Logprobs */
            top_logprobs: components["schemas"]["ChatCompletionTokenTopLogprob"][];
        };
        /** ChatCompletionTokenTopLogprob */
        ChatCompletionTokenTopLogprob: {
            /** Token */
            token: string;
            /** Logprob */
            logprob: number;
            /** Bytes */
            bytes: number[] | null;
        };
        /** ChatCompletionTool */
        ChatCompletionTool: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "function";
            function: components["schemas"]["FunctionObject"];
        };
        /** ChoiceLogprobs */
        ChoiceLogprobs: {
            /** Content */
            content: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
            /** Refusal */
            refusal: components["schemas"]["ChatCompletionTokenLogprob"][] | null;
        };
        /** CompletionUsage */
        CompletionUsage: {
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        ContentPart: components["schemas"]["InputTextContent"] | components["schemas"]["OutputTextContent"] | components["schemas"]["InputImageContent"] | components["schemas"]["_Loose"];
        /** CreateChatCompletionRequest */
        CreateChatCompletionRequest: {
            /** Messages */
            messages: components["schemas"]["ChatCompletionRequestMessage"][];
            /** Model */
            model: string;
            /** Metadata */
            metadata?: {
                [key: string]: string;
            } | null;
            /** Top Logprobs */
            top_logprobs?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Top P */
            top_p?: number | null;
            /** User */
            user?: string | null;
            /** Safety Identifier */
            safety_identifier?: string | null;
            /** Prompt Cache Key */
            prompt_cache_key?: string | null;
            /** Prompt Cache Retention */
            prompt_cache_retention?: ("in_memory" | "24h") | null;
            prompt_cache_options?: components["schemas"]["PromptCacheOptionsParam"] | null;
            service_tier?: components["schemas"]["ServiceTier"] | null;
            /** Modalities */
            modalities?: components["schemas"]["ResponseModality"][] | null;
            verbosity?: components["schemas"]["Verbosity"] | null;
            reasoning_effort?: components["schemas"]["ReasoningEffort"] | null;
            /** Max Completion Tokens */
            max_completion_tokens?: number | null;
            /** Frequency Penalty */
            frequency_penalty?: number | null;
            /** Presence Penalty */
            presence_penalty?: number | null;
            web_search_options?: components["schemas"]["WebSearchOptions"] | null;
            /** Response Format */
            response_format?: (components["schemas"]["ResponseFormatText"] | components["schemas"]["ResponseFormatJsonSchema"] | components["schemas"]["ResponseFormatJsonObject"]) | null;
            audio?: components["schemas"]["AudioOutputParameters"] | null;
            /** Store */
            store?: boolean | null;
            moderation?: components["schemas"]["ModerationParam"] | null;
            /** Stream */
            stream?: boolean | null;
            /** Stop */
            stop?: string | string[] | null;
            /** Logit Bias */
            logit_bias?: {
                [key: string]: number;
            } | null;
            /** Logprobs */
            logprobs?: boolean | null;
            /** Max Tokens */
            max_tokens?: number | null;
            /** N */
            n?: number | null;
            prediction?: components["schemas"]["PredictionContent"] | null;
            /** Seed */
            seed?: number | null;
            stream_options?: components["schemas"]["ChatCompletionStreamOptions"] | null;
            /** Tools */
            tools?: (components["schemas"]["ChatCompletionTool"] | components["schemas"]["CustomToolChatCompletions"])[] | null;
            /** Tool Choice */
            tool_choice?: components["schemas"]["ToolChoiceMode"] | components["schemas"]["ChatCompletionAllowedToolsChoice"] | components["schemas"]["ChatCompletionNamedToolChoice"] | components["schemas"]["ChatCompletionNamedToolChoiceCustom"] | null;
            /** Parallel Tool Calls */
            parallel_tool_calls?: boolean | null;
            /** Function Call */
            function_call?: components["schemas"]["FunctionCallMode"] | components["schemas"]["ChatCompletionFunctionCallOption"] | null;
            /** Functions */
            functions?: components["schemas"]["ChatCompletionFunctions"][] | null;
        };
        /** CreateChatCompletionResponse */
        CreateChatCompletionResponse: {
            /** Id */
            id: string;
            /**
             * Object
             * @constant
             */
            object: "chat.completion";
            /** Created */
            created: number;
            /** Model */
            model: string;
            /** Choices */
            choices: components["schemas"]["CreateChatCompletionResponseChoice"][];
            usage?: components["schemas"]["CompletionUsage"] | null;
        };
        /** CreateChatCompletionResponseChoice */
        CreateChatCompletionResponseChoice: {
            /** Index */
            index: number;
            message: components["schemas"]["ChatCompletionResponseMessage"];
            logprobs: components["schemas"]["ChoiceLogprobs"] | null;
            finish_reason: components["schemas"]["FinishReason"];
        };
        /** CreateResponse */
        CreateResponse: {
            /** Metadata */
            metadata?: {
                [key: string]: string;
            } | null;
            /** Top Logprobs */
            top_logprobs?: number | null;
            /** Temperature */
            temperature?: number | null;
            /** Top P */
            top_p?: number | null;
            /** User */
            user?: string | null;
            /** Safety Identifier */
            safety_identifier?: string | null;
            /** Prompt Cache Key */
            prompt_cache_key?: string | null;
            /** Prompt Cache Retention */
            prompt_cache_retention?: ("in_memory" | "24h") | null;
            /** Prompt Cache Options */
            prompt_cache_options?: {
                [key: string]: unknown;
            } | null;
            /** Previous Response Id */
            previous_response_id?: string | null;
            /** Model */
            model?: string | null;
            /** Background */
            background?: boolean | null;
            /** Max Tool Calls */
            max_tool_calls?: number | null;
            text?: components["schemas"]["ResponseTextParam"] | null;
            /** Tools */
            tools?: components["schemas"]["Tool"][] | null;
            tool_choice?: components["schemas"]["ToolChoiceParam"] | null;
            /** Prompt */
            prompt?: {
                [key: string]: unknown;
            } | null;
            /** Access Programs */
            access_programs?: {
                [key: string]: unknown;
            } | null;
            /** Service Tier */
            service_tier?: string | null;
            /** Truncation */
            truncation?: ("auto" | "disabled") | null;
            reasoning?: components["schemas"]["Reasoning"] | null;
            input?: components["schemas"]["InputParam"] | null;
            /** Include */
            include?: components["schemas"]["IncludeEnum"][] | null;
            /** Parallel Tool Calls */
            parallel_tool_calls?: boolean | null;
            /** Store */
            store?: boolean | null;
            /** Instructions */
            instructions?: string | null;
            /** Moderation */
            moderation?: {
                [key: string]: unknown;
            } | null;
            /** Stream */
            stream?: boolean | null;
            /** Stream Options */
            stream_options?: {
                [key: string]: unknown;
            } | null;
            /** Conversation */
            conversation?: string | {
                [key: string]: unknown;
            } | null;
            /** Context Management */
            context_management?: {
                [key: string]: unknown;
            }[] | null;
            /** Max Output Tokens */
            max_output_tokens?: number | null;
        };
        /** CustomToolChatCompletions */
        CustomToolChatCompletions: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "custom";
            custom: components["schemas"]["CustomToolChatCompletionsBody"];
        };
        /** CustomToolChatCompletionsBody */
        CustomToolChatCompletionsBody: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Format */
            format?: {
                [key: string]: unknown;
            } | null;
        };
        /** EasyInputMessage */
        EasyInputMessage: {
            /** Type */
            type?: "message" | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "system" | "developer";
            /** Content */
            content: string | components["schemas"]["ContentPart"][];
        };
        /** @enum {string} */
        Endpoint: "/v1/chat/completions" | "/v1/responses";
        /** FileContent */
        FileContent: {
            /** Filename */
            filename?: string | null;
            /** File Data */
            file_data?: string | null;
            /** File Id */
            file_id?: string | null;
        };
        /**
         * FinishReason
         * @enum {string}
         */
        FinishReason: "stop" | "length" | "tool_calls" | "content_filter" | "function_call";
        /** FunctionCall */
        FunctionCall: {
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
        };
        /**
         * FunctionCallMode
         * @enum {string}
         */
        FunctionCallMode: "none" | "auto";
        /** FunctionCallOutputItemParam */
        FunctionCallOutputItemParam: {
            /** Id */
            id?: string | null;
            /** Call Id */
            call_id?: string | null;
            /**
             * Type
             * @default function_call_output
             * @constant
             */
            type: "function_call_output";
            /** Output */
            output: string | {
                [key: string]: unknown;
            }[];
        };
        /** FunctionObject */
        FunctionObject: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        };
        /** FunctionTool */
        FunctionTool: {
            /**
             * Type
             * @constant
             */
            type: "function";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Parameters */
            parameters?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        };
        /** FunctionToolCall */
        FunctionToolCall: {
            /** Id */
            id?: string | null;
            /**
             * Type
             * @default function_call
             * @constant
             */
            type: "function_call";
            /** Call Id */
            call_id: string;
            /** Name */
            name: string;
            /** Arguments */
            arguments: string;
            status?: components["schemas"]["ResponseStatus"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /**
         * ImageDetail
         * @enum {string}
         */
        ImageDetail: "auto" | "low" | "high" | "original";
        /** ImageUrl */
        ImageUrl: {
            /** Url */
            url: string;
            detail?: components["schemas"]["ImageDetail"] | null;
        };
        /**
         * IncludeEnum
         * @enum {string}
         */
        IncludeEnum: "file_search_call.results" | "web_search_call.results" | "web_search_call.action.sources" | "message.input_image.image_url" | "computer_call_output.output.image_url" | "code_interpreter_call.outputs" | "reasoning.encrypted_content" | "message.output_text.logprobs";
        /** IncompleteDetails */
        IncompleteDetails: {
            /**
             * Reason
             * @constant
             */
            reason: "max_output_tokens";
        };
        /** InputAudio */
        InputAudio: {
            /** Data */
            data: string;
            /**
             * Format
             * @enum {string}
             */
            format: "wav" | "mp3";
        };
        /** InputImageContent */
        InputImageContent: {
            /**
             * Type
             * @constant
             */
            type: "input_image";
            /** Image Url */
            image_url?: string | null;
            /** File Id */
            file_id?: string | null;
            /** Detail */
            detail?: string | null;
        };
        InputItem: components["schemas"]["EasyInputMessage"] | components["schemas"]["InputMessage"] | components["schemas"]["OutputMessage"] | components["schemas"]["FunctionToolCall"] | components["schemas"]["FunctionCallOutputItemParam"] | components["schemas"]["ReasoningItem"] | components["schemas"]["_Loose"];
        /** InputMessage */
        InputMessage: {
            /** Type */
            type?: "message" | null;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "system" | "developer";
            status?: components["schemas"]["ResponseStatus"] | null;
            /** Content */
            content: components["schemas"]["ContentPart"][];
        };
        InputParam: string | components["schemas"]["InputItem"][];
        /** InputTextContent */
        InputTextContent: {
            /**
             * Type
             * @constant
             */
            type: "input_text";
            /** Text */
            text: string;
        };
        /** InputTokensDetails */
        InputTokensDetails: {
            /**
             * Cached Tokens
             * @default 0
             */
            cached_tokens: number;
            /**
             * Cache Write Tokens
             * @default 0
             */
            cache_write_tokens: number;
        };
        /** JsonSchemaFormat */
        JsonSchemaFormat: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Schema */
            schema?: {
                [key: string]: unknown;
            } | null;
            /** Strict */
            strict?: boolean | null;
        };
        /** ListModelsResponse */
        ListModelsResponse: {
            /**
             * Object
             * @constant
             */
            object: "list";
            /** Data */
            data: components["schemas"]["Model"][];
        };
        /** LogProb */
        LogProb: {
            /** Token */
            token: string;
            /** Logprob */
            logprob: number;
            /** Bytes */
            bytes: number[];
            /** Top Logprobs */
            top_logprobs: components["schemas"]["LogProbTop"][];
        };
        /** LogProbTop */
        LogProbTop: {
            /** Token */
            token: string;
            /** Logprob */
            logprob: number;
            /** Bytes */
            bytes: number[];
        };
        /** Model */
        Model: {
            /** Id */
            id: string;
            /** Created */
            created: number;
            /**
             * Object
             * @constant
             */
            object: "model";
            /** Owned By */
            owned_by: string;
        };
        /** ModerationParam */
        ModerationParam: {
            /** Model */
            model: string;
            /** Policy */
            policy?: {
                [key: string]: unknown;
            } | null;
        };
        OutputItem: components["schemas"]["OutputMessage"] | components["schemas"]["FunctionToolCall"];
        /** OutputMessage */
        OutputMessage: {
            /** Id */
            id: string;
            /**
             * Type
             * @default message
             * @constant
             */
            type: "message";
            /**
             * Role
             * @default assistant
             * @constant
             */
            role: "assistant";
            /** Content */
            content: components["schemas"]["ContentPart"][];
            status: components["schemas"]["ResponseStatus"];
        };
        /** OutputTextContent */
        OutputTextContent: {
            /**
             * Type
             * @constant
             */
            type: "output_text";
            /** Text */
            text: string;
            /**
             * Annotations
             * @default []
             */
            annotations: {
                [key: string]: unknown;
            }[];
            /**
             * Logprobs
             * @default []
             */
            logprobs: components["schemas"]["LogProb"][];
        };
        /** OutputTokensDetails */
        OutputTokensDetails: {
            /**
             * Reasoning Tokens
             * @default 0
             */
            reasoning_tokens: number;
        };
        /**
         * Participant
         * @enum {string}
         */
        Participant: "client" | "api" | "ollama";
        /** PredictionContent */
        PredictionContent: {
            /**
             * Type
             * @constant
             */
            type: "content";
            /** Content */
            content: string | components["schemas"]["TextParts"];
        };
        /** PromptCacheBreakpointParam */
        PromptCacheBreakpointParam: {
            /**
             * Mode
             * @constant
             */
            mode: "explicit";
        };
        /** PromptCacheOptionsParam */
        PromptCacheOptionsParam: {
            /** Ttl */
            ttl?: "30m" | null;
            /** Mode */
            mode?: ("implicit" | "explicit") | null;
        };
        /** Reasoning */
        Reasoning: {
            /** Mode */
            mode?: string | null;
            effort?: components["schemas"]["ReasoningEffort"] | null;
            /** Summary */
            summary?: ("auto" | "concise" | "detailed") | null;
            /** Context */
            context?: ("auto" | "current_turn" | "all_turns") | null;
            /** Generate Summary */
            generate_summary?: ("auto" | "concise" | "detailed") | null;
        };
        /**
         * ReasoningEffort
         * @enum {string}
         */
        ReasoningEffort: "none" | "minimal" | "low" | "medium" | "high" | "xhigh" | "max";
        /** ReasoningItem */
        ReasoningItem: {
            /** Id */
            id: string;
            /**
             * Type
             * @constant
             */
            type: "reasoning";
            /**
             * Summary
             * @default []
             */
            summary: {
                [key: string]: unknown;
            }[];
        };
        /**
         * RequestStatus
         * @enum {string}
         */
        RequestStatus: "succeeded" | "failed" | "cancelled";
        /** Response */
        Response: {
            /** Id */
            id: string;
            /**
             * Object
             * @default response
             * @constant
             */
            object: "response";
            /** Created At */
            created_at: number;
            /** Completed At */
            completed_at: number | null;
            status: components["schemas"]["ResponseStatus"];
            /** Model */
            model: string;
            /** Output */
            output: components["schemas"]["OutputItem"][];
            usage: components["schemas"]["ResponseUsage"] | null;
            error: components["schemas"]["ResponseError"] | null;
            incomplete_details: components["schemas"]["IncompleteDetails"] | null;
            /** Instructions */
            instructions: string | null;
            /** Metadata */
            metadata: {
                [key: string]: string;
            };
            /** Tools */
            tools: {
                [key: string]: unknown;
            }[];
            /** Tool Choice */
            tool_choice: string | {
                [key: string]: unknown;
            };
            /** Temperature */
            temperature: number | null;
            /** Top P */
            top_p: number | null;
            /** Parallel Tool Calls */
            parallel_tool_calls: boolean;
            /** Max Output Tokens */
            max_output_tokens: number | null;
            /** Text */
            text: {
                [key: string]: unknown;
            };
            /**
             * Truncation
             * @enum {string}
             */
            truncation: "auto" | "disabled";
            /** Reasoning */
            reasoning: {
                [key: string]: unknown;
            } | null;
            /** Top Logprobs */
            top_logprobs: number | null;
            /** Access Programs */
            access_programs?: {
                [key: string]: unknown;
            } | null;
            /**
             * Background
             * @default false
             */
            background: boolean;
            /** Previous Response Id */
            previous_response_id?: string | null;
        };
        /** ResponseError */
        ResponseError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ResponseFormatJsonObject */
        ResponseFormatJsonObject: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "json_object";
        };
        /** ResponseFormatJsonSchema */
        ResponseFormatJsonSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "json_schema";
            json_schema: components["schemas"]["JsonSchemaFormat"];
        };
        /** ResponseFormatText */
        ResponseFormatText: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        /**
         * ResponseModality
         * @enum {string}
         */
        ResponseModality: "text" | "audio";
        /**
         * ResponseStatus
         * @enum {string}
         */
        ResponseStatus: "completed" | "incomplete" | "in_progress" | "failed" | "cancelled";
        /** ResponseTextParam */
        ResponseTextParam: {
            format?: components["schemas"]["TextResponseFormatConfiguration"] | null;
            /** Verbosity */
            verbosity?: ("low" | "medium" | "high") | null;
        };
        /** ResponseUsage */
        ResponseUsage: {
            /** Input Tokens */
            input_tokens: number;
            /**
             * @default {
             *       "cached_tokens": 0,
             *       "cache_write_tokens": 0
             *     }
             */
            input_tokens_details: components["schemas"]["InputTokensDetails"];
            /** Output Tokens */
            output_tokens: number;
            /**
             * @default {
             *       "reasoning_tokens": 0
             *     }
             */
            output_tokens_details: components["schemas"]["OutputTokensDetails"];
            /** Total Tokens */
            total_tokens: number;
        };
        /**
         * ServiceTier
         * @enum {string}
         */
        ServiceTier: "auto" | "default" | "flex" | "scale" | "priority" | "fast";
        /**
         * StepKind
         * @enum {string}
         */
        StepKind: "request_received" | "sent_to_ollama" | "received_from_ollama" | "response_returned" | "error";
        /**
         * StepStatus
         * @enum {string}
         */
        StepStatus: "in_progress" | "completed" | "failed" | "canceled" | "interrupted";
        TextParts: components["schemas"]["ChatCompletionRequestMessageContentPartText"][];
        TextResponseFormatConfiguration: components["schemas"]["ResponseFormatText"] | components["schemas"]["ResponseFormatJsonObject"] | components["schemas"]["TextResponseFormatJsonSchema"];
        /** TextResponseFormatJsonSchema */
        TextResponseFormatJsonSchema: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "json_schema";
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Schema */
            schema: {
                [key: string]: unknown;
            };
            /** Strict */
            strict?: boolean | null;
        };
        Tool: components["schemas"]["FunctionTool"] | components["schemas"]["_Loose"];
        /** ToolChoiceAllowed */
        ToolChoiceAllowed: {
            /**
             * Type
             * @constant
             */
            type: "allowed_tools";
            /**
             * Mode
             * @enum {string}
             */
            mode: "auto" | "required";
            /** Tools */
            tools: {
                [key: string]: unknown;
            }[];
        };
        /** ToolChoiceFunction */
        ToolChoiceFunction: {
            /**
             * Type
             * @constant
             */
            type: "function";
            /** Name */
            name: string;
        };
        /**
         * ToolChoiceMode
         * @enum {string}
         */
        ToolChoiceMode: "none" | "auto" | "required";
        /**
         * ToolChoiceOptions
         * @enum {string}
         */
        ToolChoiceOptions: "none" | "auto" | "required";
        ToolChoiceParam: components["schemas"]["ToolChoiceOptions"] | components["schemas"]["ToolChoiceFunction"] | components["schemas"]["ToolChoiceAllowed"] | components["schemas"]["_Loose"];
        /**
         * TraceOutcome
         * @enum {string}
         */
        TraceOutcome: "in_progress" | "success" | "error" | "canceled" | "interrupted";
        /** TracedRequestDetail */
        TracedRequestDetail: {
            /** Id */
            id: number;
            /** Endpoint */
            endpoint: string;
            /** Method */
            method: string;
            /** Started At */
            started_at: number;
            /** Started At Ms */
            started_at_ms: number;
            /** Duration Ms */
            duration_ms: number | null;
            /** Http Status */
            http_status: number | null;
            outcome: components["schemas"]["TraceOutcome"];
            /** Summary */
            summary: string | null;
            /** Response Id */
            response_id: string | null;
            /** Error Message */
            error_message: string | null;
            /** Steps */
            steps: components["schemas"]["WorkflowStepItem"][];
        };
        /** TracedRequestItem */
        TracedRequestItem: {
            /** Id */
            id: number;
            /** Endpoint */
            endpoint: string;
            /** Method */
            method: string;
            /** Started At */
            started_at: number;
            /** Started At Ms */
            started_at_ms: number;
            /** Duration Ms */
            duration_ms: number | null;
            /** Http Status */
            http_status: number | null;
            outcome: components["schemas"]["TraceOutcome"];
            /** Summary */
            summary: string | null;
            /** Response Id */
            response_id: string | null;
            /** Error Message */
            error_message: string | null;
        };
        /** TracedRequestList */
        TracedRequestList: {
            /**
             * Object
             * @constant
             */
            object: "list";
            /** Data */
            data: components["schemas"]["TracedRequestItem"][];
            /** First Id */
            first_id: number | null;
            /** Last Id */
            last_id: number | null;
            /** Has More */
            has_more: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Verbosity
         * @enum {string}
         */
        Verbosity: "low" | "medium" | "high";
        /** WebSearchLocation */
        WebSearchLocation: {
            /** Country */
            country?: string | null;
            /** Region */
            region?: string | null;
            /** City */
            city?: string | null;
            /** Timezone */
            timezone?: string | null;
        };
        /** WebSearchOptions */
        WebSearchOptions: {
            user_location?: components["schemas"]["WebSearchUserLocation"] | null;
            /** Search Context Size */
            search_context_size?: ("low" | "medium" | "high") | null;
        };
        /** WebSearchUserLocation */
        WebSearchUserLocation: {
            /**
             * Type
             * @constant
             */
            type: "approximate";
            approximate: components["schemas"]["WebSearchLocation"];
        };
        /** WorkflowStepItem */
        WorkflowStepItem: {
            /** Position */
            position: number;
            kind: components["schemas"]["StepKind"];
            source: components["schemas"]["Participant"];
            destination: components["schemas"]["Participant"];
            status: components["schemas"]["StepStatus"];
            /** Offset Ms */
            offset_ms: number;
            /** Duration Ms */
            duration_ms: number | null;
            /** Content */
            content: unknown;
            /** Error Message */
            error_message: string | null;
        };
        /** _Loose */
        _Loose: {
            /** Type */
            type?: string | null;
        } & {
            [key: string]: unknown;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_chat_completion_v1_chat_completions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatCompletionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateChatCompletionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_response_v1_responses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResponse"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Response"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListModelsResponse"];
                };
            };
        };
    };
    list_requests_v1_analytics_requests_get: {
        parameters: {
            query?: {
                limit?: number;
                after?: string | null;
                endpoint?: components["schemas"]["Endpoint"] | null;
                status?: components["schemas"]["RequestStatus"] | null;
                since?: number | null;
                until?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRequestList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_requests_summary_v1_analytics_requests_summary_get: {
        parameters: {
            query?: {
                endpoint?: components["schemas"]["Endpoint"] | null;
                status?: components["schemas"]["RequestStatus"] | null;
                since?: number | null;
                until?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsRequestSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_v1_observability_requests_get: {
        parameters: {
            query?: {
                limit?: number;
                after?: number | null;
                endpoint?: string | null;
                outcome?: components["schemas"]["TraceOutcome"][] | null;
                since?: number | null;
                until?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracedRequestList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_v1_observability_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TracedRequestDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_events_v1_observability_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
