[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AlixPa", email = "81264144+AlixPa@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "anyio>=4.14.2",
    "db",
    "fastapi>=0.141.1",
    "llm",
    "uvicorn>=0.54.0",
]

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
db = { workspace = true }
llm = { workspace = true }

[dependency-groups]
dev = [
    "openai>=3.24.0",
    "openapi-core>=0.23.1",
]
