[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "AlixPa", email = "81264144+AlixPa@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "asyncpg>=0.31.0",
    "db",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "python-multipart>=0.0.32",
    "rich>=15.0.0",
    "uvicorn[standard]>=0.52.4",
]

[build-system]
requires = ["uv_build>=0.9.25,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
db = { workspace = true }
